### PR TITLE
Build in Ubuntu 23.04

### PR DESCRIPTION
**Pull request by lucasw**
I've made a few edits to make this build in 23.04 and eliminate some warnings but it's not quite there, cuda isn't working:

```
In file included from /usr/include/cuda_runtime.h:83,
                 from <command-line>:
/usr/include/crt/host_config.h:132:2: error: #error -- unsupported GNU version! gcc versions later than 11 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
  132 | #error -- unsupported GNU version! gcc versions later than 11 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
      |  ^~~~~
CMake Error at lvr2cuda_static_generated_CudaSurface.cu.o.Release.cmake:220 (message):
  Error generating
  /home/lucasw/base_catkin_ws/build/lvr2/src/liblvr2/CMakeFiles/lvr2cuda_static.dir/reconstruction/cuda/./lvr2cuda_static_generated_CudaSurface.cu.o
```

I thought the above may have been caused by forcing C++ to an older standard than the nvcc that is in 23.04 but possibly my system isn't set up properly.

If older Ubuntu versions (<18.04 or other non-Ubuntu systems?) are still being supported there could be more logic around those to restore setting `c++11`- but if only current LTS systems are targeted it should be safe to remove.

### CODE REVIEW

**Comment by aock** [comment]
Hi Lucas,

thanks for your contributions! On top of your state, we made some changes so that lvr2 compiles with Ubuntu 22 and ROS2 - humble. The CUDA things are also compiling and running again. And it is already merged: https://github.com/uos/lvr2/pull/16. It seemed easier for us to do it this way. So this PR is not required anymore.

Greetings
Alex
